
export const PERMISSIONS = {

  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  VIEW_USERS: "VIEW_USERS",


  CREATE_ROLE: "CREATE_ROLE",
  UPDATE_ROLE: "UPDATE_ROLE",
  DELETE_ROLE: "DELETE_ROLE",
  VIEW_ROLES: "VIEW_ROLES",


  CREATE_DEPARTMENT: "CREATE_DEPARTMENT",
  UPDATE_DEPARTMENT: "UPDATE_DEPARTMENT",
  DELETE_DEPARTMENT: "DELETE_DEPARTMENT",
  VIEW_DEPARTMENTS: "VIEW_DEPARTMENTS",


  CREATE_PROJECT: "CREATE_PROJECT",
  UPDATE_PROJECT: "UPDATE_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  VIEW_PROJECTS: "VIEW_PROJECTS",

  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",

  MANAGE_SYSTEM: "MANAGE_SYSTEM",

  // Sales Permissions
  MANAGE_LEADS: "MANAGE_LEADS",
  VIEW_LEADS: "VIEW_LEADS",
  UPDATE_LEAD_STATUS: "UPDATE_LEAD_STATUS",
  MANAGE_EMAILS: "MANAGE_EMAILS",
  MANAGE_MEETINGS: "MANAGE_MEETINGS",
  MANAGE_FOLLOW_UPS: "MANAGE_FOLLOW_UPS",
  VIEW_SALES_REPORTS: "VIEW_SALES_REPORTS",
  MANAGE_SALES_PIPELINE: "MANAGE_SALES_PIPELINE",
};
